sudo: required

services:
  - docker

before_script:
  - sh -c "$DOCKER_LOGIN_COMMAND" > /dev/null

script:
  - docker build -t nao20010128nao/android-build:gradle-2.14.1 gradle-2.14.1/
  - docker push nao20010128nao/android-build:gradle-2.14.1
  
  - docker build -t nao20010128nao/android-build:latest .
  - docker push nao20010128nao/android-build:latest
  
  - docker build -t nao20010128nao/android-build:ndk ndk/
  - docker push nao20010128nao/android-build:ndk
  
