echo y | android update sdk --no-ui --all --filter platform-tools | grep 'package installed'

echo y | android update sdk --no-ui --all --filter android-25 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-24 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-23 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-22 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-21 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-20 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-19 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-17 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-15 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-10 | grep 'package installed'


echo y | android update sdk --no-ui --all --filter build-tools-25.0.2 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-25.0.1 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-25.0.0 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-24.0.3 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-24.0.2 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-24.0.1 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-24.0.0 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.3 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.2 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.1 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-22.0.1 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-21.1.2 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-20.0.0 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-19.1.0 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-17.0.0 | grep 'package installed'

echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
echo y | android update sdk --no-ui --all --filter extra-google-m2repository | grep 'package installed'
echo y | android update sdk --no-ui --all --filter extra-google-google_play_services | grep 'package installed'

echo y | android update sdk --no-ui --all --filter addon-google_apis-google-23 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter addon-google_apis-google-22 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter addon-google_apis-google-21 | grep 'package installed'
