#!/bin/sh
install_sdk_package platform-tools | grep 'package installed'

install_sdk_package android-25 | grep 'package installed'
install_sdk_package android-24 | grep 'package installed'
install_sdk_package android-23 | grep 'package installed'
install_sdk_package android-22 | grep 'package installed'
install_sdk_package android-21 | grep 'package installed'
install_sdk_package android-20 | grep 'package installed'
install_sdk_package android-19 | grep 'package installed'
install_sdk_package android-17 | grep 'package installed'
install_sdk_package android-15 | grep 'package installed'
install_sdk_package android-10 | grep 'package installed'


install_sdk_package build-tools-25.0.2 | grep 'package installed'
install_sdk_package build-tools-25.0.1 | grep 'package installed'
install_sdk_package build-tools-25.0.0 | grep 'package installed'
install_sdk_package build-tools-24.0.3 | grep 'package installed'
install_sdk_package build-tools-24.0.2 | grep 'package installed'
install_sdk_package build-tools-24.0.1 | grep 'package installed'
install_sdk_package build-tools-24.0.0 | grep 'package installed'
install_sdk_package build-tools-23.0.3 | grep 'package installed'
install_sdk_package build-tools-23.0.2 | grep 'package installed'
install_sdk_package build-tools-23.0.1 | grep 'package installed'
install_sdk_package build-tools-22.0.1 | grep 'package installed'
install_sdk_package build-tools-21.1.2 | grep 'package installed'
install_sdk_package build-tools-20.0.0 | grep 'package installed'
install_sdk_package build-tools-19.1.0 | grep 'package installed'
install_sdk_package build-tools-17.0.0 | grep 'package installed'

install_sdk_package extra-android-m2repository | grep 'package installed'
install_sdk_package extra-google-m2repository | grep 'package installed'
install_sdk_package extra-google-google_play_services | grep 'package installed'

install_sdk_package addon-google_apis-google-23 | grep 'package installed'
install_sdk_package addon-google_apis-google-22 | grep 'package installed'
install_sdk_package addon-google_apis-google-21 | grep 'package installed'
